version: "3.8"
services:
  mysql_db:
    container_name: api-db
    image: mysql/mysql-server:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=011223
      - MYSQL_DATABASE=users_db
    ports:
      - "3306:3306"
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - users_db_data:/var/lib/mysql
  api:
    container_name: users-api
    build: ./api
    volumes:
      - ./api:/code
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
  app:
    container_name: users-app
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    depends_on:
      - api

volumes:
  users_db_data:
